# Generated by Django 6.0.6 on 2026-06-14 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('leads', 'Leads Report'), ('pipeline', 'Pipeline Report'), ('revenue', 'Revenue Report'), ('team', 'Team Performance'), ('custom', 'Custom Report')], max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('schedule', models.CharField(blank=True, max_length=100)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.organization')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
